version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:1.17.0
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    container_name: php
    build:
      context: ./docker/php
    environment:
      PHP_IDE_CONFIG: 'serverName=localhost'
    ports:
      - '8080:9000'
    volumes:
      - .:/var/www/html
      - ./docker/php/php-fpm.d/docker.conf:/usr/local/etc/php-fpm.d/docker.conf:ro
      - ./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php-fpm.d/xdebug.conf:/usr/local/etc/php-fpm.d/xdebug.conf:ro
      - ./docker/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./docker/php/php.ini-develop:/usr/local/etc/php/php.ini:ro
      - ./docker/php/bash-completions/artisan:/usr/share/bash-completion/completions/artisan:ro

  mysql:
    container_name: mysql
    image: mysql:5.7.26
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      DB_PASS: ${DB_PASS}
volumes:
  mysql:
